routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\Backend;


Route::group(array('middleware' => ['auth','web']), function () {
	Route::get('/', [Backend\Dashboard\DashboardController::class, 'index'])->name('dashboard');

	Route::controller(Backend\Settings\ProfileController::class)->group(function () {
		Route::prefix('settings')->group(function () {
		   Route::get('/profile', 'index');
    		Route::post('/profile', 'update');
    		Route::post('/change-password', 'changePassword');
    		Route::delete('/profile/delete', 'delete');
		});    	
	});

	Route::controller(Backend\Settings\UsersController::class)->group(function () {
		Route::group(array('prefix'=>'settings','middleware' => ['role:Super Admin|Admin']),function () {
    		Route::get('/users', 'index');
    		Route::delete('/users/delete/{user_id}', 'delete');
    		Route::get('/users/create', 'create');
    		Route::post('/users/create', 'store');
    		Route::get('/users/edit/{user_id}', 'edit');
    		Route::post('/users/edit/{user_id}', 'update');
		});    	
	});

	Route::controller(Backend\Core\MasterJobsController::class)->group(function () {
		Route::group(array('prefix'=>'master-jobs'),function () {
    		Route::get('/list', 'index');
    		Route::get('/list-datatables', 'datatables');
    		Route::get('/create', 'create');
    		Route::post('/create', 'store');
    		Route::get('/edit/{mjob_id}', 'edit');
    		Route::post('/edit/{mjob_id}', 'update');
    		Route::delete('/delete/{mjob_id}', 'delete');
		});    	
	});

	// Project Files
	Route::resource('master-jobs.project_files', Backend\Core\ProjectFilesController::class)->except(['show']);
	Route::get('master-job/{mjob_id}/project_files/list-datatables', [Backend\Core\ProjectFilesController::class, 'datatables']);

	// Equipments
	Route::resource('equipments', Backend\Core\EquipmentController::class)->except(['show']);
	Route::get('/equipments/list-datatables', [Backend\Core\EquipmentController::class, 'datatables']);

	// organization
	Route::resource('organizations', Backend\Core\OrganizationController::class)->except(['show']);
	Route::get('/organizations/list-datatables', [Backend\Core\OrganizationController::class, 'datatables']);


	// Contacts
	Route::resource('contacts', Backend\Core\ContactController::class)->except(['show']);
	Route::get('/contacts/list-datatables', [Backend\Core\ContactController::class, 'datatables']);

	Route::controller(Backend\Validation\ParselyValidation::class)->group(function () {
		Route::prefix('validation')->group(function () {
    		Route::post('/unique-email/{user_id}', 'validate_email')->name('validate.email');
    		Route::post('/validateoptions', 'validateoptions')->name('validate.option');
		});    	
	});

});

Auth::routes(['register' => false]);

app/Http/Controllers/Backend/Core/ContactController.php
<?php

namespace App\Http\Controllers\Backend\Core;

use App\Http\Controllers\Controller;
use App\Models\Contact;
use Illuminate\Http\Request;
use DataTables;
use App\Models\Organization;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.core.contact.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function datatables()
    {
        $contacts=Contact::with('organization:org_id,org_name');

		return Datatables::eloquent($contacts)						  
			->addColumn('action', function ($contact) {
					  return $contact->c_id;
				 })
			->addColumn('org', function ($contact) {
				if ($contact->organization) {
					return $contact->organization->org_name;
				} else {
					return null;
				}
				
			})
			->rawColumns(['action'])                   
			->make(true); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    	$orgs=Organization::pluck('org_name','org_id');
        return view('backend.core.contact.create',compact('orgs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       	$this->validate($request, [
	         'c_first_name' => 'required', 
	         'c_last_name' => 'required', 
	         'c_email' => 'nullable|email', 
	         'c_type' => 'nullable|in:'.implode(',', config('master.contacts.type')), 
	    ], [
	             
	    ]);

	    try {
            Contact::create($request->all());
         } catch (Exception $e) {
            return back()->with('error','Oops! Something Went Wrong.');
         }
        
        return redirect('contacts')->with('success','New Contact Added!');
    }
    

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit($c_id)
    {
        $orgs=Organization::pluck('org_name','org_id');
        $contact=Contact::findOrFail($c_id);

        return view('backend.core.contact.edit',compact('orgs','contact'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $c_id)
    {
    	try {
            $contact=Contact::findOrFail($c_id);
        }catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return redirect()->back()->with('error','Oops! Something Went Wrong.');
        }

        $this->validate($request, [
	         'c_first_name' => 'required', 
	         'c_last_name' => 'required', 
	         'c_email' => 'nullable|email', 
	         'c_type' => 'nullable|in:'.implode(',', config('master.contacts.type')), 
	    ], [
	             
	    ]);

	    $contact = $contact->updateOrCreate(
            ['c_id' => $c_id],
            $request->all()            
        );

        return redirect('contacts')->with('success','Contact Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy($c_id)
    {
        try {
            $org=Contact::findOrFail($c_id);
            $org->delete();
        }catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return redirect()->back()->with('error','Oops! Something Went Wrong.');
        }

        return redirect()->back()->with('success','Contact Deleted!');
    }
}

app/Http/Controllers/Backend/Core/EquipmentController.php
<?php

namespace App\Http\Controllers\Backend\Core;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Equipment;
use DataTables;
use Carbon\Carbon;

class EquipmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.core.equipments.index');
    }

    public function datatables()
    {
        $equips=Equipment::query();

        return Datatables::eloquent($equips)                       
                ->addColumn('action', function ($equip) {
                    return $equip->equip_id;
                })
                ->editColumn('equip_p_date', function($equip) {
                    if ($equip->equip_p_date) {
                        return Carbon::createFromFormat('Y-m-d', $equip->equip_p_date)->format('m/d/Y');
                    }else{return null;}
                    
                })
        ->rawColumns(['action'])                   
        ->make(true); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.core.equipments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
         'equip_e_id' => 'required',  
         'equip_status' => 'required|in:'.implode(',', config('master.equipments.status')), 

         'equip_p_date' => 'date_format:m/d/Y|nullable', 
         'equip_p_cost' => 'nullable|numeric|regex:/^[0-9]*(\.[0-9]{0,2})?$/',
      ], [
            'equip_p_date.date_format' => 'Invalid Date',      
      ]);

        if ($request->equip_p_date) {
            $request->merge([
                'equip_p_date' => Carbon::createFromFormat('m/d/Y', $request->equip_p_date)->format('Y-m-d'),
            ]);
        }
        

        try {
            Equipment::create($request->all());
         } catch (Exception $e) {
            return back()->with('error','Oops! Something Went Wrong.');
         }
        
        return redirect('equipments')->with('success','New Equipment Added!');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $equip=Equipment::findOrFail($id);

        return view('backend.core.equipments.edit',compact('equip'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $equip=Equipment::findOrFail($id);
        }catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return redirect()->back()->with('error','Oops! Something Went Wrong.');
        }

        $this->validate($request, [
         'equip_e_id' => 'required',  
         'equip_status' => 'required|in:'.implode(',', config('master.equipments.status')), 

         'equip_p_date' => 'date_format:m/d/Y|nullable', 
         'equip_p_cost' => 'nullable|numeric|regex:/^[0-9]*(\.[0-9]{0,2})?$/',
      ], [
            'equip_p_date.date_format' => 'Invalid Date',      
      ]);

        if ($request->equip_p_date) {
            $request->merge([
                'equip_p_date' => Carbon::createFromFormat('m/d/Y', $request->equip_p_date)->format('Y-m-d'),
            ]);
        }
        

        try {
            $equip->updateOrCreate(
                ['equip_id' => $id],
                $request->all()            
            );
         } catch (Exception $e) {
            return back()->with('error','Oops! Something Went Wrong.');
         }
        
        return redirect('equipments')->with('success','Equipment Detail Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $org=Equipment::findOrFail($id);
            $org->delete();
        }catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return redirect()->back()->with('error','Oops! Something Went Wrong.');
        }

        return redirect()->back()->with('success',$org->equip_e_id.' Deleted!');
    }
}

app/Http/Controllers/Backend/Core/OrganizationController.php
<?php

namespace App\Http\Controllers\Backend\Core;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Organization;
use DataTables;

class OrganizationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.core.oraganizations.index');
    }

    public function datatables()
    {
        $orgs=Organization::withCount('masterJobs');

        return Datatables::eloquent($orgs)                        
            ->addColumn('action', function ($org) {
                      return $org->org_id;
                 })
            ->rawColumns(['action'])                   
            ->make(true); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.core.oraganizations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreOrganizationRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'org_name' => 'required|unique:organizations,org_name',       
            'org_email' => 'nullable|email',        
            'org_type' => 'required|in:'.implode(',', config('master.organizations.type')), 
         ], [
                
         ]);

         try {
            Organization::create($request->all());
         } catch (Exception $e) {
            return back()->with('error','Oops! Something Went Wrong.');
         }
        
        return redirect('organizations')->with('success','New Organization Created!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function edit($org_id)
    {
        $org=Organization::findOrFail($org_id);
        return view('backend.core.oraganizations.edit',compact('org'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateOrganizationRequest  $request
     * @param  \App\Models\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $org_id)
    {
        try {
            $org=Organization::findOrFail($org_id);
        }catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return redirect()->back()->with('error','Oops! Something Went Wrong.');
        }

        $this->validate($request, [
            'org_name' => 'required|unique:organizations,org_name,'.$org_id.',org_id',       
            'org_email' => 'nullable|email',        
            'org_type' => 'required|in:'.implode(',', config('master.organizations.type')), 
         ], [
                
         ]);

        

        $flight = $org->updateOrCreate(
            ['org_id' => $org->org_id],
            $request->all()            
        );

        return redirect('organizations')->with('success',$org->org_name.' Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function destroy($org_id)
    {
        try {
            $org=Organization::findOrFail($org_id);
            $org->delete();
        }catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return redirect()->back()->with('error','Oops! Something Went Wrong.');
        }

        return redirect('organizations')->with('success',$org->org_name.' Deleted!');
    }
}

resources/views/backend/core/oraganizations/edit.blade.php
@extends('adminlte::page')

@section('title_prefix', 'Edit Organization - ')

@section('content_header')
    <h1>Edit Organization</h1>
@stop

@section('content')

   <div class="card card-navy">
      <div class="card-header">
         <h3 class="card-title">Edit Organization</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
      </div>


      <div class="card-body">
         <div class="row justify-content-center">
            <div class="col-md-9 offset-md-3">
                <form class="form-horizontal" action="{{route('organizations.update', $org->org_id)}}" method="POST" name="form" id="myForm" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    {{-- first name --}}
                    <div class="form-group row m-b-17 {{ $errors->has('org_name') ? 'has-error' : ''}}" >
                        <label for="org_name" class="col-md-1 col-form-label">Name <span class="text-danger">*</span></label>
                        <div class="col-md-7 error-block">
                            {!!Form::text('org_name',                      
                                $org->org_name,
                                array(
                                    'data-parsley-group'=>'step-member', 
                                    'data-parsley-required'=>'true',
                                    'data-parsley-required-message'=>'Name is Required',
                                    'data-parsley-trigger'=> 'change focusout',
                                    'value' => Input::old('org_name'),
                                    'placeholder'=>'- -',
                                    'id'=>'org_name',
                                    'class'=>'form-control',
                                    'data-parsley-remote'=>url('validation/validateoptions'),
                                    'data-parsley-remote-message'=>"Organization Name Already Taken",
                                    'data-parsley-remote-options'=>'{ "type": "POST", "dataType": "jsonp", "data": { "_token": "'.csrf_token().'","table" : "organizations" , "type":"uniqueness", "table_field":"org_name", "id":"'.$org->org_id.'","filter_field":"org_id" } }'
                                    )
                            )!!}                        
                            @foreach ($errors->get('org_name') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>

                    {{-- Type --}}
                    <div class="form-group row m-b-17 {{ $errors->has('org_type') ? 'has-error' : ''}}" >
                        <label for="org_type" class="col-md-1 col-form-label">Type <span class="text-danger">*</span></label>
                        <div class="col-md-7 error-block">
                            {!!Form::select('org_type',
                                config('master.organizations.type'),
                                $org->org_type,
                                array(
                                    'data-parsley-group'=>'step-member', 
                                    'data-parsley-required'=>'true',
                                    'data-parsley-required-message'=>'Please Select Type',
                                    'data-parsley-trigger'=> 'change focusout',
                                    'value' => Input::old('org_type'),
                                    'class'=>'form-control',
                                    'data-size'=>'10',
                                    'id'=>'client',
                                    'data-live-search'=>'false',
                                    'data-style'=>'btn-white',
                                    'tabindex'=>'-98',
                                    'placeholder'=>'--Select Type--'
                                    )
                            )!!}                                
                            @foreach ($errors->get('org_type') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>

                    {{-- phone --}}
                    <div class="form-group row m-b-17 {{ $errors->has('org_phone') ? 'has-error' : ''}}" >
                        <label for="org_phone" class="col-md-1 col-form-label">Phone </label>
                        <div class="col-md-7 error-block">
                            {!!Form::text('org_phone',                      
                                $org->org_phone,
                                array(
                                    'data-parsley-group'=>'step-member',                                   
                                    'data-parsley-trigger'=> 'change focusout',
                                    'value' => Input::old('org_phone'),
                                    'placeholder'=>'- -',
                                    'id'=>'org_phone',
                                    'class'=>'form-control',
                                    'data-inputmask'=>"'mask':'(999) 999-9999'",
                                    'inputmode'=>"text"
                                    )
                            )!!}                        
                            @foreach ($errors->get('phone') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>

                    {{-- fax --}}
                    <div class="form-group row m-b-17 {{ $errors->has('org_fax') ? 'has-error' : ''}}" >
                        <label for="org_fax" class="col-md-1 col-form-label">Fax </label>
                        <div class="col-md-7 error-block">
                            {!!Form::text('org_fax',                      
                                $org->org_fax,
                                array(
                                    'data-parsley-group'=>'step-member',                                   
                                    'data-parsley-trigger'=> 'change focusout',
                                    'value' => Input::old('org_fax'),
                                    'placeholder'=>'- -',
                                    'id'=>'org_fax',
                                    'class'=>'form-control',
                                    )
                            )!!}                        
                            @foreach ($errors->get('org_fax') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>

                    {{-- email --}}
                    <div class="form-group row m-b-17 {{ $errors->has('org_email') ? 'has-error' : ''}}" >
                        <label for="org_email" class="col-md-1 col-form-label">Email </label>
                        <div class="col-md-7 error-block">
                            {!!Form::email('org_email',                      
                                $org->org_email,
                                array(
                                    'data-parsley-group'=>'step-member',                                   
                                    'data-parsley-trigger'=> 'change focusout',
                                    'data-parsley-type-message'=>'Please Enter a Valid Email Address',
                                    'data-parsley-type'=>'email', 
                                    'value' => Input::old('org_email'),
                                    'placeholder'=>'- -',
                                    'id'=>'org_email',
                                    'class'=>'form-control',
                                    )
                            )!!}                        
                            @foreach ($errors->get('org_email') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>

                    {{-- address --}}
                    <div class="form-group row m-b-17 {{ $errors->has('org_address') ? 'has-error' : ''}}" >
                        <label for="org_address" class="col-md-1 col-form-label">Address </label>
                        <div class="col-md-7 error-block">
                            {!!Form::text('org_address',                      
                                $org->org_address,
                                array(
                                    'data-parsley-group'=>'step-member',                                   
                                    'data-parsley-trigger'=> 'change focusout',
                                    'value' => Input::old('org_address'),
                                    'placeholder'=>'- -',
                                    'id'=>'org_address',
                                    'class'=>'form-control',
                                    )
                            )!!}                        
                            @foreach ($errors->get('org_address') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="offset-sm-2 col-md-7">
                            <button type="submit" class="btn btn-custom" id="submit_info">Update</button>
                        </div>
                    </div>
                </form>
            </div>

          </div>
      </div>
        <!-- /.card-body -->
   </div>
@stop

@section('css')
    
@stop

@section('js')
    <script src="{{asset('vendor/parsley/dist/parsley.js')}}"></script>  
    <script src="{{asset('vendor/inputmask/jquery.inputmask.min.js')}}"></script>  

    <script>
        // parsely

        $('#submit_info').on('click', function(e, anchorObject, stepNumber, stepDirection) {
            var res = $('form[name="form"]').parsley().validate('step-member');
            return res;
        });
        $("#org_phone").inputmask({"mask": "(999) 999-9999"});
    </script>

@stop