routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\Backend;


Route::group(array('middleware' => ['auth','web']), function () {
	Route::get('/', [Backend\Dashboard\DashboardController::class, 'index'])->name('dashboard');

	Route::controller(Backend\Settings\ProfileController::class)->group(function () {
		Route::prefix('settings')->group(function () {
		   Route::get('/profile', 'index');
    		Route::post('/profile', 'update');
    		Route::post('/change-password', 'changePassword');
    		Route::delete('/profile/delete', 'delete');
		});    	
	});

	Route::controller(Backend\Settings\UsersController::class)->group(function () {
		Route::group(array('prefix'=>'settings','middleware' => ['role:Super Admin|Admin']),function () {
    		Route::get('/users', 'index');
    		Route::delete('/users/delete/{user_id}', 'delete');
    		Route::get('/users/create', 'create');
    		Route::post('/users/create', 'store');
    		Route::get('/users/edit/{user_id}', 'edit');
    		Route::post('/users/edit/{user_id}', 'update');
		});    	
	});

	Route::controller(Backend\Core\MasterJobsController::class)->group(function () {
		Route::group(array('prefix'=>'master-jobs'),function () {
    		Route::get('/list', 'index');
    		Route::get('/list-datatables', 'datatables');
    		Route::get('/create', 'create');
    		Route::post('/create', 'store');
    		Route::get('/edit/{mjob_id}', 'edit');
    		Route::post('/edit/{mjob_id}', 'update');
    		Route::delete('/delete/{mjob_id}', 'delete');
		});    	
	});

	// Project Files
	Route::resource('master-jobs.project_files', Backend\Core\ProjectFilesController::class)->except(['show']);
	Route::get('master-job/{mjob_id}/project_files/list-datatables', [Backend\Core\ProjectFilesController::class, 'datatables']);

	// Equipments
	Route::resource('equipments', Backend\Core\EquipmentController::class)->except(['show']);
	Route::get('/equipments/list-datatables', [Backend\Core\EquipmentController::class, 'datatables']);

	// organization
	Route::resource('organizations', Backend\Core\OrganizationController::class)->except(['show']);
	Route::get('/organizations/list-datatables', [Backend\Core\OrganizationController::class, 'datatables']);


	// Contacts
	Route::resource('contacts', Backend\Core\ContactController::class)->except(['show']);
	Route::get('/contacts/list-datatables', [Backend\Core\ContactController::class, 'datatables']);

	Route::controller(Backend\Validation\ParselyValidation::class)->group(function () {
		Route::prefix('validation')->group(function () {
    		Route::post('/unique-email/{user_id}', 'validate_email')->name('validate.email');
    		Route::post('/validateoptions', 'validateoptions')->name('validate.option');
		});    	
	});

});

Auth::routes(['register' => false]);

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Contact extends Model
{
   use HasFactory,SoftDeletes;

   protected $primaryKey = 'c_id';

   protected $dates = ['deleted_at'];

   protected $guarded = ['c_id','deleted_at'];
   
   public $timestamps = false;

   public function organization()
   {
      return $this->belongsTo(Organization::class,'organization_id');
   }
}

app/Http/Controllers/Backend/Core/ContactController.php
<?php

namespace App\Http\Controllers\Backend\Core;

use App\Http\Controllers\Controller;
use App\Models\Contact;
use Illuminate\Http\Request;
use DataTables;
use App\Models\Organization;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.core.contact.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function datatables()
    {
        $contacts=Contact::with('organization:org_id,org_name');

		return Datatables::eloquent($contacts)						  
			->addColumn('action', function ($contact) {
					  return $contact->c_id;
				 })
			->addColumn('org', function ($contact) {
				if ($contact->organization) {
					return $contact->organization->org_name;
				} else {
					return null;
				}
				
			})
			->rawColumns(['action'])                   
			->make(true); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    	$orgs=Organization::pluck('org_name','org_id');
        return view('backend.core.contact.create',compact('orgs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       	$this->validate($request, [
	         'c_first_name' => 'required', 
	         'c_last_name' => 'required', 
	         'c_email' => 'nullable|email', 
	         'c_type' => 'nullable|in:'.implode(',', config('master.contacts.type')), 
	    ], [
	             
	    ]);

	    try {
            Contact::create($request->all());
         } catch (Exception $e) {
            return back()->with('error','Oops! Something Went Wrong.');
         }
        
        return redirect('contacts')->with('success','New Contact Added!');
    }
    

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit($c_id)
    {
        $orgs=Organization::pluck('org_name','org_id');
        $contact=Contact::findOrFail($c_id);

        return view('backend.core.contact.edit',compact('orgs','contact'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $c_id)
    {
    	try {
            $contact=Contact::findOrFail($c_id);
        }catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return redirect()->back()->with('error','Oops! Something Went Wrong.');
        }

        $this->validate($request, [
	         'c_first_name' => 'required', 
	         'c_last_name' => 'required', 
	         'c_email' => 'nullable|email', 
	         'c_type' => 'nullable|in:'.implode(',', config('master.contacts.type')), 
	    ], [
	             
	    ]);

	    $contact = $contact->updateOrCreate(
            ['c_id' => $c_id],
            $request->all()            
        );

        return redirect('contacts')->with('success','Contact Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy($c_id)
    {
        try {
            $org=Contact::findOrFail($c_id);
            $org->delete();
        }catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return redirect()->back()->with('error','Oops! Something Went Wrong.');
        }

        return redirect()->back()->with('success','Contact Deleted!');
    }
}

app/Http/Controllers/Backend/Core/EquipmentController.php
<?php

namespace App\Http\Controllers\Backend\Core;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Equipment;
use DataTables;
use Carbon\Carbon;

class EquipmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.core.equipments.index');
    }

    public function datatables()
    {
        $equips=Equipment::query();

        return Datatables::eloquent($equips)                       
                ->addColumn('action', function ($equip) {
                    return $equip->equip_id;
                })
                ->editColumn('equip_p_date', function($equip) {
                    if ($equip->equip_p_date) {
                        return Carbon::createFromFormat('Y-m-d', $equip->equip_p_date)->format('m/d/Y');
                    }else{return null;}
                    
                })
        ->rawColumns(['action'])                   
        ->make(true); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.core.equipments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
         'equip_e_id' => 'required',  
         'equip_status' => 'required|in:'.implode(',', config('master.equipments.status')), 

         'equip_p_date' => 'date_format:m/d/Y|nullable', 
         'equip_p_cost' => 'nullable|numeric|regex:/^[0-9]*(\.[0-9]{0,2})?$/',
      ], [
            'equip_p_date.date_format' => 'Invalid Date',      
      ]);

        if ($request->equip_p_date) {
            $request->merge([
                'equip_p_date' => Carbon::createFromFormat('m/d/Y', $request->equip_p_date)->format('Y-m-d'),
            ]);
        }
        

        try {
            Equipment::create($request->all());
         } catch (Exception $e) {
            return back()->with('error','Oops! Something Went Wrong.');
         }
        
        return redirect('equipments')->with('success','New Equipment Added!');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $equip=Equipment::findOrFail($id);

        return view('backend.core.equipments.edit',compact('equip'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $equip=Equipment::findOrFail($id);
        }catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return redirect()->back()->with('error','Oops! Something Went Wrong.');
        }

        $this->validate($request, [
         'equip_e_id' => 'required',  
         'equip_status' => 'required|in:'.implode(',', config('master.equipments.status')), 

         'equip_p_date' => 'date_format:m/d/Y|nullable', 
         'equip_p_cost' => 'nullable|numeric|regex:/^[0-9]*(\.[0-9]{0,2})?$/',
      ], [
            'equip_p_date.date_format' => 'Invalid Date',      
      ]);

        if ($request->equip_p_date) {
            $request->merge([
                'equip_p_date' => Carbon::createFromFormat('m/d/Y', $request->equip_p_date)->format('Y-m-d'),
            ]);
        }
        

        try {
            $equip->updateOrCreate(
                ['equip_id' => $id],
                $request->all()            
            );
         } catch (Exception $e) {
            return back()->with('error','Oops! Something Went Wrong.');
         }
        
        return redirect('equipments')->with('success','Equipment Detail Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $org=Equipment::findOrFail($id);
            $org->delete();
        }catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return redirect()->back()->with('error','Oops! Something Went Wrong.');
        }

        return redirect()->back()->with('success',$org->equip_e_id.' Deleted!');
    }
}

app/Http/Controllers/Backend/Core/OrganizationController.php
<?php

namespace App\Http\Controllers\Backend\Core;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Organization;
use DataTables;

class OrganizationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.core.oraganizations.index');
    }

    public function datatables()
    {
        $orgs=Organization::withCount('masterJobs');

        return Datatables::eloquent($orgs)                        
            ->addColumn('action', function ($org) {
                      return $org->org_id;
                 })
            ->rawColumns(['action'])                   
            ->make(true); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.core.oraganizations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreOrganizationRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'org_name' => 'required|unique:organizations,org_name',       
            'org_email' => 'nullable|email',        
            'org_type' => 'required|in:'.implode(',', config('master.organizations.type')), 
         ], [
                
         ]);

         try {
            Organization::create($request->all());
         } catch (Exception $e) {
            return back()->with('error','Oops! Something Went Wrong.');
         }
        
        return redirect('organizations')->with('success','New Organization Created!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function edit($org_id)
    {
        $org=Organization::findOrFail($org_id);
        return view('backend.core.oraganizations.edit',compact('org'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateOrganizationRequest  $request
     * @param  \App\Models\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $org_id)
    {
        try {
            $org=Organization::findOrFail($org_id);
        }catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return redirect()->back()->with('error','Oops! Something Went Wrong.');
        }

        $this->validate($request, [
            'org_name' => 'required|unique:organizations,org_name,'.$org_id.',org_id',       
            'org_email' => 'nullable|email',        
            'org_type' => 'required|in:'.implode(',', config('master.organizations.type')), 
         ], [
                
         ]);

        

        $flight = $org->updateOrCreate(
            ['org_id' => $org->org_id],
            $request->all()            
        );

        return redirect('organizations')->with('success',$org->org_name.' Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function destroy($org_id)
    {
        try {
            $org=Organization::findOrFail($org_id);
            $org->delete();
        }catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return redirect()->back()->with('error','Oops! Something Went Wrong.');
        }

        return redirect('organizations')->with('success',$org->org_name.' Deleted!');
    }
}

resources/views/backend/core/contact/create.blade.php
@extends('adminlte::page')

@section('title_prefix', 'Create Contact - ')

@section('content_header')
    <h1>Create Contact</h1>
@stop

@section('content')

   <div class="card card-navy">
      <div class="card-header">
         <h3 class="card-title">Create Contact</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
      </div>


      <div class="card-body">
         <div class="row justify-content-center">
            <div class="col-md-9 offset-md-2">
                <form class="form-horizontal" action="{{route('contacts.store')}}" method="POST" name="form" id="myForm" enctype="multipart/form-data">
                    @csrf
                    @method('POST')
                    {{-- first name --}}
                    <div class="form-group row m-b-17 {{ $errors->has('c_first_name') ? 'has-error' : ''}}" >
                        <label for="c_first_name" class="col-md-2 col-form-label">First Name <span class="text-danger">*</span></label>
                        <div class="col-md-7 error-block">
                            {!!Form::text('c_first_name',                      
                                null,
                                array(
                                    'data-parsley-group'=>'step-member', 
                                    'data-parsley-required'=>'true',
                                    'data-parsley-required-message'=>'First Name is Required',
                                    'data-parsley-trigger'=> 'change focusout',
                                    'value' => Input::old('c_first_name'),
                                    'placeholder'=>'- -',
                                    'id'=>'c_first_name',
                                    'class'=>'form-control',
                                    )
                            )!!}                        
                            @foreach ($errors->get('c_first_name') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>

                    {{-- Last name --}}
                    <div class="form-group row m-b-17 {{ $errors->has('c_last_name') ? 'has-error' : ''}}" >
                        <label for="c_last_name" class="col-md-2 col-form-label">Last Name <span class="text-danger">*</span></label>
                        <div class="col-md-7 error-block">
                            {!!Form::text('c_last_name',                      
                                null,
                                array(
                                    'data-parsley-group'=>'step-member', 
                                    'data-parsley-required'=>'true',
                                    'data-parsley-required-message'=>'Last Name is Required',
                                    'data-parsley-trigger'=> 'change focusout',
                                    'value' => Input::old('c_last_name'),
                                    'placeholder'=>'- -',
                                    'id'=>'c_last_name',
                                    'class'=>'form-control',
                                    )
                            )!!}                        
                            @foreach ($errors->get('c_last_name') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>

                    {{-- Type --}}
                    <div class="form-group row m-b-17 {{ $errors->has('c_type') ? 'has-error' : ''}}" >
                        <label for="c_type" class="col-md-2 col-form-label">Type </label>
                        <div class="col-md-7 error-block">
                            {!!Form::select('c_type',
                                config('master.contacts.type'),
                                null,
                                array(                                    
                                    'value' => Input::old('c_type'),
                                    'class'=>'form-control',
                                    'data-size'=>'10',
                                    'id'=>'client',
                                    'data-live-search'=>'false',
                                    'data-style'=>'btn-white',
                                    'tabindex'=>'-98',
                                    'placeholder'=>'--Select Type--'
                                    )
                            )!!}                                
                            @foreach ($errors->get('c_type') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>

                    {{-- Organization --}}
                    <div class="form-group row m-b-17 {{ $errors->has('organization_id') ? 'has-error' : ''}}" >
                        <label for="organization_id" class="col-md-2 col-form-label">Organization </label>
                        <div class="col-md-7 error-block">
                            {!!Form::select('organization_id',
                                $orgs,
                                null,
                                array(                                    
                                    'value' => Input::old('organization_id'),
                                    'class'=>'form-control organization_id',
                                    'data-size'=>'10',
                                    'id'=>'client',
                                    'data-live-search'=>'false',
                                    'data-style'=>'btn-white',
                                    'tabindex'=>'-98',
                                    'placeholder'=>'--Select Type--'
                                    )
                            )!!}                                
                            @foreach ($errors->get('organization_id') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>                  

                    {{-- email --}}
                    <div class="form-group row m-b-17 {{ $errors->has('c_email') ? 'has-error' : ''}}" >
                        <label for="c_email" class="col-md-2 col-form-label">Email </label>
                        <div class="col-md-7 error-block">
                            {!!Form::email('c_email',                      
                                null,
                                array(
                                    'data-parsley-group'=>'step-member',                                   
                                    'data-parsley-trigger'=> 'change focusout',
                                    'data-parsley-type-message'=>'Please Enter a Valid Email Address',
                                    'data-parsley-type'=>'email', 
                                    'value' => Input::old('c_email'),
                                    'placeholder'=>'- -',
                                    'id'=>'c_email',
                                    'class'=>'form-control',
                                    )
                            )!!}                        
                            @foreach ($errors->get('c_email') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>

                    {{-- Home --}}
                    <div class="form-group row m-b-17 {{ $errors->has('c_home') ? 'has-error' : ''}}" >
                        <label for="c_home" class="col-md-2 col-form-label">Home </label>
                        <div class="col-md-7 error-block">
                            {!!Form::text('c_home',                      
                                null,
                                array(
                                    'data-parsley-group'=>'step-member',                                   
                                    'data-parsley-trigger'=> 'change focusout',
                                    'value' => Input::old('c_home'),
                                    'placeholder'=>'- -',
                                    'id'=>'c_home',
                                    'class'=>'form-control phone',
                                    'data-inputmask'=>"'mask':'(999) 999-9999'",
                                    'inputmode'=>"text"
                                    )
                            )!!}                        
                            @foreach ($errors->get('c_home') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>

                    {{-- Cell --}}
                    <div class="form-group row m-b-17 {{ $errors->has('c_cell') ? 'has-error' : ''}}" >
                        <label for="c_cell" class="col-md-2 col-form-label">Cell </label>
                        <div class="col-md-7 error-block">
                            {!!Form::text('c_cell',                      
                                null,
                                array(
                                    'data-parsley-group'=>'step-member',                                   
                                    'data-parsley-trigger'=> 'change focusout',
                                    'value' => Input::old('c_cell'),
                                    'placeholder'=>'- -',
                                    'id'=>'c_cell',
                                    'class'=>'form-control phone',
                                    'data-inputmask'=>"'mask':'(999) 999-9999'",
                                    'inputmode'=>"text"
                                    )
                            )!!}                        
                            @foreach ($errors->get('c_cell') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>

                    {{-- Work --}}
                    <div class="form-group row m-b-17 {{ $errors->has('c_work') ? 'has-error' : ''}}" >
                        <label for="c_work" class="col-md-2 col-form-label">Work </label>
                        <div class="col-md-7 error-block">
                            {!!Form::text('c_work',                      
                                null,
                                array(
                                    'data-parsley-group'=>'step-member',                                   
                                    'data-parsley-trigger'=> 'change focusout',
                                    'value' => Input::old('c_work'),
                                    'placeholder'=>'- -',
                                    'id'=>'c_work',
                                    'class'=>'form-control phone',
                                    'data-inputmask'=>"'mask':'(999) 999-9999'",
                                    'inputmode'=>"text"
                                    )
                            )!!}                        
                            @foreach ($errors->get('c_work') as $message) 
                              <p class="help-block">{{$message}}</p>
                            @endforeach
                        </div>
                    </div>
                    

                    <div class="form-group row">
                        <div class="offset-sm-2 col-md-7">
                            <button type="submit" class="btn btn-custom" id="submit_info">Create</button>
                        </div>
                    </div>
                </form>
            </div>

          </div>
      </div>
        <!-- /.card-body -->
   </div>
@stop

@section('css')
    <link href="{{asset('vendor/select2/css/select2.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendor/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}" rel="stylesheet">
@stop

@section('js')
    <script src="{{asset('vendor/parsley/dist/parsley.js')}}"></script>  
    <script src="{{asset('vendor/inputmask/jquery.inputmask.min.js')}}"></script> 
    <script src="{{asset('vendor/select2/js/select2.min.js')}}"></script> 

    <script>
        // parsely

        $('#submit_info').on('click', function(e, anchorObject, stepNumber, stepDirection) {
            var res = $('form[name="form"]').parsley().validate('step-member');
            return res;
        });
        $(".phone").inputmask({"mask": "(999) 999-9999"});
    </script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('.organization_id').select2({
                placeholder: "- -",
                allowClear: true
            });
        });
    </script>

@stop